name: Pull Request Check

on:
  workflow_call:
    inputs:
      pr-title-regex:
        description: Regex to match for PR title
        # https://regex101.com/r/RBKHec/1
        # Slightly more relaxed than the one given below:
        # https://gist.github.com/marcojahn/482410b728c31b221b70ea6d2c433f0c
        default: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\([\w\-\.]+\))?(!)?: ([\s\S]*)'
        required: false
        type: string

      pr-body-regex:
        description: Regex to match for PR body
        default: '.*'
        required: false
        type: string

jobs:
  pr-title-check:
    name: Check PR title and body
    runs-on: ubuntu-latest
    steps:
      - name: title-checker
        id: title-checker
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
        with:
          pr-title-regex: ${{ inputs.pr-title-regex }}
          pr-body-regex: ${{ inputs.pr-body-regex }}
