name: Rust Build

on:
  workflow_call:
    inputs:
      targets:
        description: |
          JSON-formatted list of target platforms. See https://doc.rust-lang.org/rustc/platform-support.html
        default: "[]"
        required: false
        type: string

      options:
        description: |
          Build options. See https://doc.rust-lang.org/cargo/commands/cargo-build.html#options
        required: false
        type: string

      ################################################################################
      #
      # setup-rust related inputs
      #
      ################################################################################
      cache-shared-key:
        description: Cache key used instead of the default job-based key.
        required: false
        type: string

      cache-key:
        description: Cache key appended to the default job-based key.
        required: false
        type: string

      cargo-registry-use-custom-github-auth:
        description: Whether to configure cargo with authentication to Github. Defaults to `false`.
        default: false
        required: false
        type: boolean

      cargo-registry-github-app-owner:
        description: Github App owner used for cargo registry authentication.
        default: ${{ github.repository_owner }}
        required: false
        type: string

    secrets:
      CARGO_REGISTRY_GITHUB_APP_ID:
        required: false

      CARGO_REGISTRY_GITHUB_APP_PRIVATE_KEY:
        required: false

jobs:
  build:
    name: Build
    if: inputs.targets == '[]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup rust
        uses: a-homelab/github-actions/actions/setup-rust@main
        with:
          cache-shared-key: ${{ inputs.cache-shared-key }}
          cache-key: ${{ inputs.cache-key }}
          cargo-registry-use-custom-github-auth: ${{ inputs.cargo-registry-use-custom-github-auth }}
          cargo-registry-github-app-id: ${{ secrets.CARGO_REGISTRY_GITHUB_APP_ID }}
          cargo-registry-github-app-private-key: ${{ secrets.CARGO_REGISTRY_GITHUB_APP_PRIVATE_KEY }}
          cargo-registry-github-app-owner: ${{ inputs.cargo-registry-github-app-owner }}

      - name: Build
        uses: a-homelab/github-actions/actions/rust-build@main
        with:
          options: ${{ inputs.options }}

  build-cross:
    name: Build (Cross)
    if: inputs.targets != '[]'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(inputs.targets) }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup rust
        uses: a-homelab/github-actions/actions/setup-rust@main

      - name: Build
        uses: a-homelab/github-actions/actions/rust-build-cross@main
        with:
          target: ${{ matrix.target }}
          options: ${{ inputs.options }}
