name: Rust Build and Test

on:
  workflow_call:
    inputs:
      build-options:
        description: |
          Build options. See https://doc.rust-lang.org/cargo/commands/cargo-build.html#options
        required: false
        type: string

      test-options:
        description: |
          Test options. See https://nexte.st/docs/running/#options-and-arguments
        required: false
        type: string
      
      ################################################################################
      #
      # setup-rust related inputs
      #
      ################################################################################
      cache-shared-key:
        description: Cache key used instead of the default job-based key.
        required: false
        type: string

      cache-key:
        description: Cache key appended to the default job-based key.
        required: false
        type: string

      cargo-registry-use-custom-github-auth:
        description: Whether to configure cargo with authentication to Github. Defaults to `false`.
        default: false
        required: false
        type: boolean
      
      cargo-registry-github-app-id-secret-name:
        description: Name of the secret containing the Github App id used for cargo registry authentication.
        default: CARGO_REGISTRY_GITHUB_APP_ID
        required: false
        type: string

      cargo-registry-github-app-private-key-secret-name:
        description: Name of the secret containing the Github App private key used for cargo registry authentication.
        default: CARGO_REGISTRY_GITHUB_APP_PRIVATE_KEY
        required: false
        type: string
      
      cargo-registry-github-app-owner:
        description: Github App owner used for cargo registry authentication.
        default: ${{ github.repository_owner }}
        required: false
        type: string

    secrets:
      CARGO_REGISTRY_GITHUB_APP_ID:
        required: false

      CARGO_REGISTRY_GITHUB_APP_PRIVATE_KEY:
        required: false

      CODECOV_TOKEN:
        required: false

jobs:
  build-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup rust
        uses: a-homelab/github-actions/actions/setup-rust@main
        with:
          cache-shared-key: ${{ inputs.cache-shared-key }}
          cache-key: ${{ inputs.cache-key }}
          cargo-registry-use-custom-github-auth: ${{ inputs.cargo-registry-use-custom-github-auth }}
          cargo-registry-github-app-id: ${{ secrets[inputs.cargo-registry-github-app-id-secret-name] }}
          cargo-registry-github-app-private-key: ${{ secrets[inputs.cargo-registry-github-app-private-key-secret-name] }}
          cargo-registry-github-app-owner: ${{ inputs.cargo-registry-use-custom-github-auth }}
      
      - name: Build
        uses: a-homelab/github-actions/actions/rust-build@main
        with:
          options: ${{ inputs.build-options }}

      - name: Test
        uses: a-homelab/github-actions/actions/rust-test@main
        with:
          upload-coverage: "true"
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          options: ${{ inputs.test-options }}
